name: azure terragrunt 

on:
  workflow_dispatch:
    inputs:

      type_of_usecase:
        type: choice
        description: use case type
        options:
          - Select Use Case
          - Single Module RG
          - Single Use Case VM
          - All Modules
        required: true

jobs:
  single_rg:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.type_of_usecase == 'Single Module RG' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Setup terragrunt
        uses: eLco/setup-terragrunt@v1

      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Running Terragrunt Init 
        run: |
          cd terragrunt/environments/dev/rg
          terragrunt init

      - name: Running Terragrunt Plan
        run: |
          cd terragrunt/environments/dev/rg
          terragrunt plan

