name: azure terragrunt 

on:
  workflow_dispatch:
    inputs:

      type_of_usecase:
        type: choice
        description: use case type
        options:
          - Select Use Case
          - Single Module RG
          - Single Use Case VM
          - All Modules
        required: true

jobs:
  single_rg:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.type_of_usecase == 'Single Module RG' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Setup terragrunt
        uses: eLco/setup-terragrunt@v1

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Running Terragrunt Init 
        run: |
          cd terragrunt/environments/dev/rg
          terragrunt init

      - name: Running Terragrunt Plan
        run: |
          cd terragrunt/environments/dev/rg
          terragrunt plan

